
// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A pricing suggestion AI agent.
 *
 * - suggestPricing - A function that handles the pricing suggestion process.
 * - SuggestPricingInput - The input type for the suggestPricing function.
 * - SuggestPricingOutput - The return type for the suggestPricing function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPricingInputSchema = z.object({
  serviceType: z
    .string()
    .describe(
      'The type of service for which the pricing is being requested (e.g., Digital Marketing, AI & Automation, Web Development, IT Implementation).'
    ),
  requirements: z
    .string()
    .describe(
      'A detailed description of the clients specific requirements for the selected service.'
    ),
});
export type SuggestPricingInput = z.infer<typeof SuggestPricingInputSchema>;

const SuggestPricingOutputSchema = z.object({
  estimatedPriceRange: z
    .string()
    .describe(
      'An estimated price range for the requested service in Indian Rupees (INR), based on the provided requirements. Please include the INR currency symbol (₹).'
    ),
});
export type SuggestPricingOutput = z.infer<typeof SuggestPricingOutputSchema>;

export async function suggestPricing(input: SuggestPricingInput): Promise<SuggestPricingOutput> {
  return suggestPricingFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPricingPrompt',
  input: {schema: SuggestPricingInputSchema},
  output: {schema: SuggestPricingOutputSchema},
  prompt: `You are an AI pricing assistant for Apex Digital Group, a full-service digital agency catering to the Indian market.

You will receive a service type and a description of the client's requirements. Based on this information, you will provide an estimated price range for the service in Indian Rupees (INR). Ensure the currency symbol (₹) is included in your response (e.g., ₹50,000 - ₹75,000).

Service Type: {{{serviceType}}}
Requirements: {{{requirements}}}

Please provide a price range in INR that is both realistic and attractive to potential clients in India.
`, config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const suggestPricingFlow = ai.defineFlow(
  {
    name: 'suggestPricingFlow',
    inputSchema: SuggestPricingInputSchema,
    outputSchema: SuggestPricingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
