
// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A pricing suggestion AI agent for the Indian market.
 *
 * - suggestPricing - A function that handles the pricing suggestion process.
 * - SuggestPricingInput - The input type for the suggestPricing function.
 * - SuggestPricingOutput - The return type for the suggestPricing function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit'; // Added Zod import from genkit
import {
  SuggestPricingInputSchema,
  type SuggestPricingInput,
  SuggestPricingOutputSchema,
  type SuggestPricingOutput
} from '@/ai/schemas/pricing-schemas';
import { services as offeredServicesList } from '@/data/mock';

export type { SuggestPricingInput, SuggestPricingOutput };

export async function suggestPricing(input: SuggestPricingInput): Promise<SuggestPricingOutput> {
  const offeredServiceTitles = offeredServicesList.map(s => s.title);
  return suggestPricingFlow({ ...input, offeredServiceTitles });
}

const ExtendedSuggestPricingInputSchema = SuggestPricingInputSchema.extend({
  offeredServiceTitles: z.array(z.string()).describe("A list of service titles that Apex Digital Group offers.")
});

const prompt = ai.definePrompt({
  name: 'suggestPricingPrompt',
  input: {schema: ExtendedSuggestPricingInputSchema},
  output: {schema: SuggestPricingOutputSchema},
  prompt: `You are an AI pricing assistant for Apex Digital Group, a full-service digital agency catering exclusively to the Indian market.

You will receive a service type and a description of the client's requirements.
Apex Digital Group offers the following services:
{{#each offeredServiceTitles}}
- {{{this}}}
{{/each}}

IMPORTANT:
- First, check if the requested 'Service Type: {{{serviceType}}}' is one of the services listed above.
- If the 'Service Type: {{{serviceType}}}' is NOT in the list of offered services, you MUST set the 'estimatedPriceRange' to "Apex Digital Group does not currently offer '{{{serviceType}}}'. Please select from our available services." and 'estimatedTimeline' to "Not Applicable". Do NOT attempt to estimate a price for unlisted services.
- If the 'Service Type: {{{serviceType}}}' IS in the list of offered services, then you will provide:
  1. An estimated price range for the service in Indian Rupees (INR).
  2. An estimated timeline for project completion (e.g., "2-4 weeks", "1-2 months", "Approx. 6 weeks").
- You MUST use the Indian Rupee symbol (₹) exclusively for currency when providing a price. Do NOT use "INR", "Rs.", or any other abbreviations or currency names. For example, a correct price response would be "₹50,000 - ₹75,000".
- Both the price and the timeline are estimates and should be presented as such if a service is offered.

Service Type: {{{serviceType}}}
Requirements: {{{requirements}}}

Based on the above, proceed.
`, config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const suggestPricingFlow = ai.defineFlow(
  {
    name: 'suggestPricingFlow',
    inputSchema: ExtendedSuggestPricingInputSchema, // Use extended schema
    outputSchema: SuggestPricingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output) {
      // Fallback in case the model fails to produce an output, though the prompt should guide it.
      return {
        estimatedPriceRange: "Could not generate an estimate at this time.",
        estimatedTimeline: "Not Applicable"
      };
    }
    return output;
  }
);

