
// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A pricing suggestion AI agent for the Indian market.
 *
 * - suggestPricing - A function that handles the pricing suggestion process.
 * - SuggestPricingInput - The input type for the suggestPricing function.
 * - SuggestPricingOutput - The return type for the suggestPricing function.
 */

import {ai} from '@/ai/genkit';
import {
  SuggestPricingInputSchema,
  type SuggestPricingInput,
  SuggestPricingOutputSchema,
  type SuggestPricingOutput
} from '@/ai/schemas/pricing-schemas';

export type { SuggestPricingInput, SuggestPricingOutput };

export async function suggestPricing(input: SuggestPricingInput): Promise<SuggestPricingOutput> {
  return suggestPricingFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPricingPrompt',
  input: {schema: SuggestPricingInputSchema},
  output: {schema: SuggestPricingOutputSchema},
  prompt: `You are an AI pricing assistant for Apex Digital Group, a full-service digital agency catering exclusively to the Indian market.

You will receive a service type and a description of the client's requirements. Based on this information, you will provide:
1. An estimated price range for the service in Indian Rupees (INR).
2. An estimated timeline for project completion (e.g., "2-4 weeks", "1-2 months", "Approx. 6 weeks").

IMPORTANT:
- You MUST use the Indian Rupee symbol (₹) exclusively for currency. Do NOT use "INR", "Rs.", or any other abbreviations or currency names. For example, a correct price response would be "₹50,000 - ₹75,000".
- Both the price and the timeline are estimates and should be presented as such.

Service Type: {{{serviceType}}}
Requirements: {{{requirements}}}

Please provide a price range and timeline that are both realistic and attractive to potential clients in India, strictly using the ₹ symbol for currency.
`, config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const suggestPricingFlow = ai.defineFlow(
  {
    name: 'suggestPricingFlow',
    inputSchema: SuggestPricingInputSchema,
    outputSchema: SuggestPricingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

